version: "3.3"
services:
  db:
    hostname: db
    image: postgres:latest
    ports:
      - "5432:5432"
    env_file:
      - ./.env
  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - ./.env
    ports:
      - "5050:80"
    depends_on:
      - db
  app:
    hostname: app
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - db
    env_file:
      - ./.env
    volumes:
      - ./bcoin/:/home/app/web/bcoin
