# Generated by Django 4.0 on 2021-12-17 00:49

from django.db import migrations


def create_initial_transaction_id(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    TransactionId = apps.get_model("coins", "TransactionId")
    TransactionId.objects.create()


def remove_initial_transaction_id(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    TransactionId = apps.get_model("coins", "TransactionId")
    TransactionId.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("coins", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(
            create_initial_transaction_id, remove_initial_transaction_id
        ),
    ]
