# Generated by Django 4.0 on 2021-12-17 01:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("coins", "0003_alter_wallet_user_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wallet",
            name="user_id",
        ),
    ]
