# Generated by Django 4.0 on 2021-12-17 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0004_remove_wallet_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='discord_id',
            field=models.CharField(default=7, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
