# Generated by Django 4.0 on 2021-12-25 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("coins", "0006_auto_20211224_2113"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cointransfer",
            name="wallet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="coins.wallet"
            ),
        ),
    ]
